### ISSUE TITLE
python.png went missing when changing the build system

### ISSUE THREAD

**Issue by ceamac** [samschott/desktop-notifier#16]
* Desktop Notifier version: 3.3.3
* Python version: 3.9
* Operating System: Gentoo Linux

### Description
resources/python.png is missing in v3.3.3

### What I Did

```
$ maestral start
Starting Maestral...Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/maestral/daemon.py", line 375, in start_maestral_daemon
    from .main import Maestral
  File "/usr/lib/python3.9/site-packages/maestral/main.py", line 41, in <module>
    from .sync import SyncDirection
  File "/usr/lib/python3.9/site-packages/maestral/sync.py", line 69, in <module>
    from . import notify
  File "/usr/lib/python3.9/site-packages/maestral/notify.py", line 13, in <module>
    from desktop_notifier import DesktopNotifier, Urgency, Button
  File "/usr/lib/python3.9/site-packages/desktop_notifier/__init__.py", line 2, in <module>
    from .main import DesktopNotifier, Button, ReplyField, Notification, Urgency
  File "/usr/lib/python3.9/site-packages/desktop_notifier/main.py", line 30, in <module>
    from .base import (
  File "/usr/lib/python3.9/site-packages/desktop_notifier/base.py", line 21, in <module>
    PYTHON_ICON_PATH = path("desktop_notifier.resources", "python.png").__enter__()
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.9/site-packages/desktop_notifier/resources/python.png'
```

**Comment by samschott** [comment]
Ah, damn, that must have been a mistake when migrating from `setup.py` to `setup.cfg`.
