### ISSUE TITLE
ValueError: No method was found starting with 'addObject' and with keywords set()

### ISSUE THREAD

**Issue by QuaCKeReD** [samschott/desktop-notifier#20]
* Operating System: macOS 12.3 Intel chip

### Description
As per https://github.com/samschott/maestral/issues/516#issuecomment-1026782249
and request to log https://github.com/samschott/maestral/issues/516#issuecomment-1027245681

When starting the sync via terminal, following error is generated;
```
Notification failed
Traceback (most recent call last):
  File "Contents/Resources/app_packages/rubicon/objc/api.py", line 206, in __call__
KeyError: frozenset({''})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Contents/Resources/app_packages/desktop_notifier/base.py", line 204, in send
  File "Contents/Resources/app_packages/desktop_notifier/macos.py", line 252, in _send
  File "Contents/Resources/app_packages/desktop_notifier/macos.py", line 366, in _create_category_for_notification
  File "Contents/Resources/app_packages/rubicon/objc/api.py", line 236, in __call__
  File "Contents/Resources/app_packages/rubicon/objc/api.py", line 215, in __call__
  File "Contents/Resources/app_packages/rubicon/objc/api.py", line 153, in __call__
  File "Contents/Resources/app_packages/rubicon/objc/api.py", line 1519, in ns_from_py
  File "Contents/Resources/app_packages/rubicon/objc/api.py", line 236, in __call__
  File "Contents/Resources/app_packages/rubicon/objc/api.py", line 208, in __call__
ValueError: No method was found starting with 'addObject' and with keywords set()
Known keywords are:
frozenset({'toPropertyWithKey', ''})
frozenset({'', 'toBothSidesOfRelationshipWithKey'})
```

**Comment by samschott** [comment]
This should be fixed with recent releases of rubicon-objc which made significant improvements to loading of ObjC methods.
