### ISSUE TITLE
[macOS] Segfault when initialising notification centre outside of framework or app bundle

### ISSUE THREAD

**Issue by rafidka** [SamSchott/desktop-notifier#8]
**Describe the bug**

I used to be able to run Maestral on macOS, but not anymore, and I wonder whether it is related to macOS Big Sur upgrade (or perhaps another upgrade?).

**To Reproduce**
1. Install `miniconda`.
2. Create a Python environment: `conda create -n dropbox python=3.8`, then activate it.
3. Start maestral with `maestral start`.

At this point, I got this error:

```
Starting Maestral...        [FAILED]
Please check logs for more information.
```

**Expected behaviour**
Maestral daemon should run.

**System:**

 - Maestral version: 1.4.4
 - Python version: 3.8
 - OS: [e.g. Ubuntu] macOS
 - Desktop environment: [e.g. Gnome 3.32] macOS
 - PyQt version (for Linux GUI): N/A

**Additional context**

When I show the logs with `maestral logs show`, I see the following:

```
2021-06-20 12:08:29 daemon ERROR: Could not communicate with daemon
Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 278, in connect_and_handshake
    sock = socketutil.create_socket(connect=connect_location,
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/socketutil.py", line 283, in create_socket
    sock.connect(connect)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 617, in start_maestral_daemon_process
    wait_for_startup(config_name, timeout)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 407, in wait_for_startup
    raise exc
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 403, in wait_for_startup
    maestral_daemon._pyroBind()
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 182, in _pyroBind
    return self.__pyroCreateConnection(True)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 342, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 304, in connect_and_handshake
    raise errors.CommunicationError(err) from x
Pyro5.errors.CommunicationError: cannot connect to /Users/rafidka/Library/Application Support/maestral/maestral.sock: [Errno 2] No such file or directory
2021-06-20 12:08:29 daemon ERROR: Daemon stopped with return code -6
2021-06-20 12:12:02 daemon ERROR: Could not communicate with daemon
Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 278, in connect_and_handshake
    sock = socketutil.create_socket(connect=connect_location,
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/socketutil.py", line 283, in create_socket
    sock.connect(connect)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 617, in start_maestral_daemon_process
    wait_for_startup(config_name, timeout)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 407, in wait_for_startup
    raise exc
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 403, in wait_for_startup
    maestral_daemon._pyroBind()
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 182, in _pyroBind
    return self.__pyroCreateConnection(True)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 342, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 304, in connect_and_handshake
    raise errors.CommunicationError(err) from x
Pyro5.errors.CommunicationError: cannot connect to /Users/rafidka/Library/Application Support/maestral/maestral.sock: [Errno 2] No such file or directory
2021-06-20 12:12:02 daemon ERROR: Daemon stopped with return code -6
2021-06-20 12:29:30 daemon ERROR: Could not communicate with daemon
Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 278, in connect_and_handshake
    sock = socketutil.create_socket(connect=connect_location,
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/socketutil.py", line 283, in create_socket
    sock.connect(connect)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 617, in start_maestral_daemon_process
    wait_for_startup(config_name, timeout)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 407, in wait_for_startup
    raise exc
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 403, in wait_for_startup
    maestral_daemon._pyroBind()
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 182, in _pyroBind
    return self.__pyroCreateConnection(True)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 342, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 304, in connect_and_handshake
    raise errors.CommunicationError(err) from x
Pyro5.errors.CommunicationError: cannot connect to /Users/rafidka/Library/Application Support/maestral/maestral.sock: [Errno 2] No such file or directory
2021-06-20 12:29:30 daemon ERROR: Daemon stopped with return code -6

```

I tried to manually execute the daemon from Python and this is what I see:

```
>>> import maestral.daemon
>>> maestral.daemon.start_maestral_daemon('maestral', True)
2021-06-20 12:26:11.732 python[43518:841675] *** Assertion failure in +[UNUserNotificationCenter currentNotificationCenter], UNUserNotificationCenter.m:54
2021-06-20 12:26:11.732 python[43518:841675] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'bundleProxyForCurrentProcess is nil: mainBundle.bundleURL file:///Users/rafidka/miniconda3/envs/dropbox/bin/'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2079887b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff204d0d92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff207c19e2 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff2157d512 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UserNotifications                   0x00007fff2a691540 __53+[UNUserNotificationCenter currentNotificationCenter]_block_invoke + 985
	5   libdispatch.dylib                   0x00007fff2047b806 _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x00007fff2047c98c _dispatch_once_callout + 20
	7   UserNotifications                   0x00007fff2a691165 +[UNUserNotificationCenter currentNotificationCenter] + 101
	8   libffi.7.dylib                      0x000000010fb45ead ffi_call_unix64 + 85
	9   ???                                 0x00007ffee0e07210 0x0 + 140732671226384
)
libc++abi: terminating with uncaught exception of type NSException
[1]    43518 abort      python
```

**Comment by rafidka** [comment]
Thanks, Sam! I appreciate the quick response. I executed the block of code above. Here is the output:

```
>>> from rubicon.objc import ObjCClass
>>> NSBundle = ObjCClass("NSBundle")
>>> main_bundle = NSBundle.mainBundle
>>> print(main_bundle.bundleURL)
file:///Users/rafidka/miniconda3/envs/dropbox/bin/
>>> print(main_bundle.bundleIdentifier)
None
```

**Comment by SamSchott** [comment]
Yes, that's certainly the issue then. No bundle identifier means no access  to the notification center for the "app".

**Comment by rafidka** [comment]
Thanks, Sam, for the quick fix. When is the change in [desktop-notifier/pull/9](https://github.com/SamSchott/desktop-notifier/pull/9) going to be live?

I am happy to help with testing as well if you give me some instructions.

**Comment by SamSchott** [comment]
Thank you for the detailed bug report! It's much easier to trouble shoot this way compared to someone just writing "it crashes on startup".

I was able to reproduce the segfault (and the fix) with a local miniconda distribution. But if you'd like to test, you can install `desktop-notifier` directly from GitHub with `pip install -U git+https://github.com/samschott/desktop-notifier`. That should solve your segfaults🤞

**Comment by SamSchott** [comment]
If it works for you, there is nothing standing in way of a quick patch release.

**Comment by rafidka** [comment]
I did install the `desktop-notifier` directly from your GitHub repository like you suggested and it worked like charm! :100: :ok_hand: :tada: :confetti_ball:

**Comment by SamSchott** [comment]
Excellent. v3.3.0 is officially released.

While it fixes the segfault, you will still not get any actual desktop notifications - you will need to install a Framework build of Python for that (preferably from python.org). The alternative would be to try and fake a valid bundle identifier at runtime. Some other packages do this but its a nasty hack and will prevent any apps using it from being accepted in the App store.
